CREATE TABLE products(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category_id INT NOT NULL,
    sku VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    unit ENUM('PCS', 'KG', 'LITRE', 'METER', 'BOX', 'SET', 'PACK', 'UNIT') NOT NULL,
    reorder_level INT DEFAULT 0,
    product_status ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP

);

ALTER TABLE products
ADD FOREIGN KEY(category_id)
REFERENCES categories(id)
ON DELETE CASCADE;